[project]
name = "navign-plot"
version = "0.1.0"
description = "Computer vision core for plotting indoor maps for indoor navigation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.76.0",
    "opencv-python>=4.12.0.88",
]
