[project]
dependencies    = ["manim>=0.19.0", "numpy>=2.3.3", "scipy>=1.16.2"]
description     = "Add your description here"
name            = "animations"
readme          = "README.md"
requires-python = ">=3.12"
version         = "0.1.0"

[tool.ruff]
lint.ignore = ["F403"]
