[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F407ZG with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32F407ZG"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
