[project]
dependencies = [
  "edge-tts>=7.2.3",
  "pvporcupine>=3.0.5",
  "pyaudio>=0.2.14",
  "pygame>=2.6.1",
  "pytest>=9.0.1",
]
description = "Add your description here"
name = "audio"
readme = "README.md"
requires-python = ">=3.14"
version = "0.1.0"
